create table if not exists public.markdown_documents (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  title text not null check (char_length(trim(title)) > 0),
  content text not null check (char_length(trim(content)) > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_markdown_documents_user_id
  on public.markdown_documents(user_id);

create index if not exists idx_markdown_documents_search
  on public.markdown_documents using gin (
    to_tsvector('english', title || ' ' || content)
  );

alter table public.markdown_documents enable row level security;

drop policy if exists "deny_direct_markdown_documents_access" on public.markdown_documents;

create policy "deny_direct_markdown_documents_access"
on public.markdown_documents
for all
to anon, authenticated
using (false)
with check (false);
