create table if not exists public.todos (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) > 0),
  completed boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.todos enable row level security;
